
project_id = "jaqzoyouuzhchuyzafii"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[functions.grok-ai]
verify_jwt = true
