
project_id = "jaqzoyouuzhchuyzafii"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.get-sustainability-suggestions]
verify_jwt = false
